version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: WinesApp
    ports:
      - "3000:3000"
    depends_on:
      - mysql_db
    environment:
      MYSQL_HOST: mysql_db
      MYSQL_PORT: 3306
      MYSQL_DATABASE: winesdb
      MYSQL_USER: admin
      MYSQL_PASSWORD: root
    restart: always

  mysql_db:
    image: mysql:8.0
    container_name: winesdb
    volumes:
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      MYSQL_DATABASE: winesdb
      MYSQL_ROOT_USER: admin
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: admin
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"
    restart: always
